{% set name = "hydra-core" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/facebookresearch/hydra/archive/v{{ version }}.tar.gz
  sha256: 3387eb8bc2ac30764855e4060c7ac49a8238cbcac2eeb87bd2db7344faa6b177

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - antlr ==4.8
  host:
    - python >=3.6,<3.9
    - pip
  run:
    - python >=3.6,<3.9
    - omegaconf >=2.0.2
    - antlr-python-runtime ==4.8
    - importlib_resources

test:
  imports:
    - hydra
  requires:
    - pytest
  source_files:
    - hydra
    - tests
    - examples
    - pytest.ini
    - ATTRIBUTION
  commands:
    - pytest -v tests/

about:
  home: https://hydra.cc/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A framework for elegantly configuring complex applications
  doc_url: https://hydra.cc/docs/intro/
  dev_url: https://github.com/facebookresearch/hydra

extra:
  recipe-maintainers:
    - mdraw
    - hadim
