{% set name = "hydra-core" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 8a878ed67216997c3e9d88a8e72e7b4767e81af37afb4ea3334b269a4390a824
    patches:
    # do not forget to update the version literal in the antlr-*-complete.jar string inside the
    # patch to correctly unvendor antlr and use the antlr package from conda
      - 0000-unvendor_antlr.patch
    folder: pypi-upstream
  - url: https://github.com/facebookresearch/hydra/archive/refs/tags/v1.3.2.tar.gz
    sha256: 3f0f14305e9c6ae4b1dbcba344fe09dd0fc79c0a0656470c249f4f7ca46bf471
    folder: test-assets

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install $SRC_DIR/pypi-upstream --no-deps --no-build-isolation -vv

requirements:
  build:
    - patch  # [not win]
    - m2-patch  # [win]
  host:
    - antlr ==4.9.*
    - python
    - pip
    - openjdk
  run:
    - python
    - omegaconf >=2.2,<2.4
    - antlr4-python3-runtime ==4.9.*
    - packaging
    - importlib_resources  # [py<39]

test:
  imports:
    - hydra
  requires:
    - pytest
  source_files:
    - test-assets/tests
    - test-assets/ATTRIBUTION
    - test-assets/pytest.ini
  commands:
    - cd test-assets/tests
    - pytest -v -W ignore::DeprecationWarning . --ignore=test_completion.py --ignore=test_hydra.py --ignore=test_compose.py --ignore=test_config_loader.py --ignore=test_examples --ignore=test_config_repository.py

about:
  home: https://hydra.cc
  license: MIT
  license_family: MIT
  license_file: pypi-upstream/LICENSE
  summary: A framework for elegantly configuring complex applications
  description: |
    Hydra is an open-source Python framework that simplifies the development of research and other complex
    applications. The key feature is the ability to dynamically create a hierarchical configuration by composition and
    override it through config files and the command line. The name Hydra comes from its ability to run multiple
    similar jobs - much like a Hydra with multiple heads.
  doc_url: https://hydra.cc/docs/intro
  dev_url: https://github.com/facebookresearch/hydra

extra:
  recipe-maintainers:
    - mdraw
    - benjaminrwilson
